<?php

declare(strict_types=1);

namespace Jackardios\ImageDimensions\Tests\Feature;

use GuzzleHttp\Psr7\Utils;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Http\Client\StrayRequestException;
use Illuminate\Support\Facades\Http;
use Jackardios\ImageDimensions\Exceptions\FileTooLargeException;
use Jackardios\ImageDimensions\Exceptions\InvalidImageException;
use Jackardios\ImageDimensions\Exceptions\TemporaryFileException;
use Jackardios\ImageDimensions\Exceptions\UrlAccessException;
use Jackardios\ImageDimensions\Exceptions\UrlNotAllowedException;
use Jackardios\ImageDimensions\ImageDimensionsService;
use Jackardios\ImageDimensions\Tests\TestCase;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;

class RemotePipelineTest extends TestCase
{
    private ImageDimensionsService $service;

    protected function setUp(): void
    {
        parent::setUp();
        // Disable caching so each assertion exercises the pipeline afresh.
        $this->service = $this->makeService();
    }

    /**
     * Build a service with caching off and the SSRF guard relaxed (these tests
     * exercise the transfer pipeline, not host filtering, and must stay
     * network-free — real DNS resolution is skipped when private hosts are
     * allowed).
     *
     * @param  array<string, mixed>  $overrides
     */
    private function makeService(array $overrides = []): ImageDimensionsService
    {
        return new ImageDimensionsService(array_merge([
            'enable_cache' => false,
            'url' => ['allow_private_hosts' => true],
        ], $overrides));
    }

    // --- URL pipeline ---

    #[Test]
    public function it_reads_dimensions_from_a_url(): void
    {
        $url = 'https://example.com/image.png';
        Http::fake([$url => Http::response(Utils::streamFor($this->imageBytes(120, 80)), 200)]);

        $this->assertDimensions(120, 80, $this->service->fromUrl($url));
    }

    #[Test]
    public function it_reads_an_svg_from_a_url_with_a_leading_comment(): void
    {
        $url = 'https://example.com/logo.svg';
        $svg = '<!-- generated by tooling --><svg xmlns="http://www.w3.org/2000/svg" width="120" height="80"><rect/></svg>';
        Http::fake([$url => Http::response($svg, 200, ['Content-Type' => 'image/svg+xml'])]);

        $this->assertDimensions(120, 80, $this->service->fromUrl($url));
    }

    /**
     * The first remote_read_bytes are not enough for either image, so the
     * rest of the body is read, from the same response.
     *
     * @return array<string, array{0: string, 1: int, 2: int}>
     */
    public static function bodyPastTheHeaderProvider(): array
    {
        return [
            'svg' => ['svg', 321, 123],
            'jpeg with large metadata' => ['jpeg', 40, 30],
        ];
    }

    #[Test]
    #[DataProvider('bodyPastTheHeaderProvider')]
    public function it_reads_the_body_past_the_header_in_a_single_request(string $kind, int $width, int $height): void
    {
        $service = $this->makeService(['remote_read_bytes' => 8192]);
        $url = "https://example.com/late.{$kind}";
        Http::fake([$url => Http::response(Utils::streamFor($this->bodyPastTheHeader($kind)), 200)]);

        $this->assertDimensions($width, $height, $service->fromUrl($url));
        Http::assertSentCount(1);
    }

    /**
     * Without a download cap the whole body is read, however long.
     */
    #[Test]
    #[DataProvider('bodyPastTheHeaderProvider')]
    public function without_a_download_cap_it_reads_the_whole_body(string $kind, int $width, int $height): void
    {
        $service = $this->makeService(['remote_read_bytes' => 8192, 'max_download_bytes' => 0, 'svg' => ['max_file_size' => 0]]);
        $url = "https://example.com/late.{$kind}";
        Http::fake([$url => Http::response(Utils::streamFor($this->bodyPastTheHeader($kind, 3000000)), 200)]);

        $this->assertDimensions($width, $height, $service->fromUrl($url));
    }

    private function bodyPastTheHeader(string $kind, int $bytes = 50000): string
    {
        return $kind === 'svg'
            ? '<svg xmlns="http://www.w3.org/2000/svg" width="321" height="123"><!--'.str_repeat('x', $bytes).'--></svg>'
            : $this->jpegWithLargeMetadata(40, 30, intdiv($bytes, 65537) + 1);
    }

    /**
     * Regression: the body stream of a response registered once with
     * Http::fake() was detached by the first request, so every later request
     * for it failed.
     */
    #[Test]
    public function a_fake_response_can_be_served_more_than_once(): void
    {
        Http::fake(['https://example.com/*' => Http::response($this->imageBytes(12, 34))]);

        $this->assertDimensions(12, 34, $this->service->fromUrl('https://example.com/a.png'));
        $this->assertDimensions(12, 34, $this->service->fromUrl('https://example.com/b.png'));
    }

    #[Test]
    public function a_stray_request_is_reported_as_such(): void
    {
        if (! class_exists(StrayRequestException::class)) {
            $this->markTestSkipped('This Laravel version reports stray requests with a plain RuntimeException.');
        }

        // Http::preventStrayRequests() is on (see TestCase): a URL a test
        // forgot to fake must not pass for an unreachable one.
        $this->expectException(StrayRequestException::class);
        $this->service->tryFromUrl('https://example.com/not-faked.png');
    }

    #[Test]
    public function it_throws_invalid_image_for_a_non_image_url_not_url_access(): void
    {
        $url = 'https://example.com/page.html';
        Http::fake([$url => Http::response('<html>not an image</html>', 200, ['Content-Type' => 'text/html'])]);

        $this->expectException(InvalidImageException::class);
        $this->service->fromUrl($url);
    }

    #[Test]
    public function it_throws_url_access_for_an_http_error_status(): void
    {
        $url = 'https://example.com/missing.png';
        Http::fake([$url => Http::response(null, 404)]);

        try {
            $this->service->fromUrl($url);
            $this->fail('Expected a UrlAccessException.');
        } catch (UrlAccessException $e) {
            // Not a subclass such as UrlNotAllowedException.
            $this->assertSame(UrlAccessException::class, $e::class);
            $this->assertSame("Could not open URL: {$url} (HTTP 404)", $e->getMessage());
        }
    }

    #[Test]
    public function a_failed_connection_is_a_url_access_error_with_its_cause(): void
    {
        $url = 'https://example.com/timeout.jpg';
        Http::fake([$url => fn () => throw new ConnectionException('Timeout was reached')]);

        try {
            $this->service->fromUrl($url);
            $this->fail('Expected a UrlAccessException.');
        } catch (UrlAccessException $e) {
            $this->assertSame("Could not open URL: {$url}", $e->getMessage());
            $this->assertInstanceOf(ConnectionException::class, $e->getPrevious());
        }
    }

    #[Test]
    public function a_redirect_loop_is_a_url_access_error(): void
    {
        $url = 'https://example.com/loop';
        $requests = 0;
        Http::fake([$url => function () use ($url, &$requests) {
            $requests++;

            return Http::response(null, 302, ['Location' => $url]);
        }]);

        try {
            $this->makeService(['url' => ['allow_private_hosts' => true, 'max_redirects' => 3]])->fromUrl($url);
            $this->fail('Expected a UrlAccessException.');
        } catch (UrlAccessException $e) {
            $this->assertSame("Could not open URL: {$url}", $e->getMessage());
            $this->assertStringContainsString('Will not follow more than 3 redirects', $this->causes($e));
        }

        // The first request and three redirects. Http::recorded() lists one
        // request more when the transfer fails, so count them here.
        $this->assertSame(4, $requests);
    }

    #[Test]
    public function a_missing_temporary_directory_is_reported(): void
    {
        $url = 'https://example.com/image.png';
        Http::fake([$url => Http::response($this->imageBytes(10, 10))]);
        $service = $this->makeService(['temp_dir' => $this->tempPath.DIRECTORY_SEPARATOR.'missing']);

        $this->expectException(TemporaryFileException::class);
        $this->expectExceptionMessage('Could not create temporary file');
        $service->fromUrl($url);
    }

    private function causes(\Throwable $e): string
    {
        $messages = [];
        for ($cause = $e; $cause !== null; $cause = $cause->getPrevious()) {
            $messages[] = $cause->getMessage();
        }

        return implode("\n", $messages);
    }

    #[Test]
    public function it_rejects_a_stream_that_exceeds_the_cap_without_a_content_length(): void
    {
        $service = $this->makeService(['remote_read_bytes' => 8192, 'max_download_bytes' => 16384]);

        $url = 'https://example.com/huge-stream';
        // 1MB of non-image bytes, no Content-Length header.
        Http::fake([$url => Http::response(Utils::streamFor(str_repeat('X', 1024 * 1024)), 200)]);

        $this->expectException(FileTooLargeException::class);
        $service->fromUrl($url);
    }

    /**
     * Regression: FileTooLargeException extends InvalidImageException, so the
     * "header was insufficient, keep reading" catch block used to swallow the
     * SVG size guard and download all the way to max_download_bytes. The SVG cap
     * must abort immediately and report itself as the SVG cap.
     */
    #[Test]
    public function it_aborts_immediately_when_the_svg_cap_is_exceeded(): void
    {
        $service = $this->makeService([
            'remote_read_bytes' => 8192,
            'max_download_bytes' => 16384,
            'svg' => ['max_file_size' => 4096],
        ]);

        $url = 'https://example.com/big.svg';
        $svg = '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10">'
            .'<!--'.str_repeat('x', 200000).'--></svg>';
        Http::fake([$url => Http::response(Utils::streamFor($svg), 200, ['Content-Type' => 'image/svg+xml'])]);

        $this->expectException(FileTooLargeException::class);
        $this->expectExceptionMessage('SVG file is too large (max 4096 bytes)');
        $service->fromUrl($url);
    }

    /**
     * Regression: with no URL path the name hint was null and the error label
     * fell back to the internal temp-file path, disclosing the server's temp
     * directory layout in a user-visible message.
     */
    #[Test]
    public function it_does_not_leak_the_temp_file_path_in_error_messages(): void
    {
        $url = 'https://example.com';
        Http::fake([$url => Http::response('not an image at all', 200)]);

        try {
            $this->service->fromUrl($url);
            $this->fail('Expected InvalidImageException');
        } catch (InvalidImageException $e) {
            $this->assertStringNotContainsString('imgdim_', $e->getMessage());
            $this->assertStringNotContainsString(sys_get_temp_dir(), $e->getMessage());
            $this->assertStringContainsString($url, $e->getMessage());
        }
    }

    // --- Storage pipeline (genuine non-local disk) ---

    #[Test]
    public function it_reads_dimensions_from_a_non_local_storage_disk(): void
    {
        $disk = $this->useInMemoryDisk('mem');
        $disk->put('photos/pic.png', $this->imageBytes(300, 150));

        $this->assertDimensions(300, 150, $this->service->fromStorage('mem', 'photos/pic.png'));
    }

    #[Test]
    public function it_throws_invalid_image_for_a_non_image_on_a_non_local_disk(): void
    {
        $disk = $this->useInMemoryDisk('mem');
        $disk->put('notes.txt', 'just some text, definitely not an image');

        $this->expectException(InvalidImageException::class);
        $this->service->fromStorage('mem', 'notes.txt');
    }

    // --- SSRF protection (enabled) ---

    #[Test]
    public function it_blocks_a_private_url_before_issuing_any_request(): void
    {
        Http::fake();
        $service = new ImageDimensionsService([
            'enable_cache' => false,
            'url' => ['allow_private_hosts' => false],
        ]);

        try {
            $service->fromUrl('http://127.0.0.1/internal.png');
            $this->fail('Expected a UrlNotAllowedException.');
        } catch (UrlNotAllowedException $e) {
            $this->addToAssertionCount(1);
        }

        Http::assertNothingSent();
    }
}
